# Generated by Django 5.1.3 on 2025-01-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background',
        ),
    ]
